### ISSUE TITLE
Running Microvium on ESP32 microcontroller

### ISSUE THREAD

**Issue by tmkasun** [coder-mike/microvium#19] opened 2022-06-15 11:34 UTC
Hi Team,

I'm interested in running JS in an ESP32 MCU, Can I run microvium on ESP32 ?
Or can you point me to the supported microcontrollers and processor architecture? 

Thanks
~Kasun

**Comment by coder-mike** [comment] 2022-06-15 22:53
Hi Kasun. Yes, it should run fine on an ESP32. It will run on any environment that supports standard C code. I designed it to be as portable as possible. My suggestion is to work through [the getting-started guide](https://github.com/coder-mike/microvium/blob/main/doc/getting-started.md) and let me know if you find anything confusing or get stuck on anything, since I want to make the process as seamless as possible for everybody and am always looking for ways to improve the experience.

I'll leave this ticket open for a bit so if you encounter any issues you can just drop a note in here.

**Comment by coder-mike** [comment] 2022-06-21 22:18
If you have no further issues then after some time I'll just close this ticket.

**Comment by tmkasun** [comment] 2022-06-22 04:47
@coder-mike , Thanks for the  information, I couldn't try that out yet, Planing to try out the microvium this weekend, I'm trying to implement a webserver to communicate with a serial communication device. I will update you once I try that out (in 3 days).

**Comment by morganrallen** [comment] 2022-06-22 19:01
I'm also taking a crack at this and have run into some build issues with a very basic setup. Here's my test repo.
https://github.com/morganrallen/esp-microvium-test

I've followed the getting started guide, including the port file but am getting a handful of build error, mostly around the expansion of the `VM_ASSERT_UNREACHABLE` macro. I'm not the best with CMake, so the issue could be there too, but the build files are really straight forward...

`microvium.c` is being included from `main/CMakeLists.txt`

```
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:956:48: warning: left shift of negative value [-Wshift-negative-value]
 #define VIRTUAL_INT14_ENCODE(i) ((uint16_t)((i << 2) | 3))
                                                ^~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:1339:29: note: in expansion of macro 'VIRTUAL_INT14_ENCODE'
   /* VM_SLV_INT_MINUS_1 */  VIRTUAL_INT14_ENCODE(-1),
                             ^~~~~~~~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c: In function 'mvm_call':
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:751:73: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_ASSERT_UNREACHABLE(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:1897:3: note: in expansion of macro 'VM_ASSERT_UNREACHABLE'
   VM_ASSERT_UNREACHABLE(vm);
   ^~~~~~~~~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:751:73: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_ASSERT_UNREACHABLE(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:2362:3: note: in expansion of macro 'VM_ASSERT_UNREACHABLE'
   VM_ASSERT_UNREACHABLE(vm);
   ^~~~~~~~~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:732:75: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_NOT_IMPLEMENTED(vm) (MVM_FATAL_ERROR(vm, MVM_E_NOT_IMPLEMENTED), -1)
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:2739:7: note: in expansion of macro 'VM_NOT_IMPLEMENTED'
       VM_NOT_IMPLEMENTED(vm);
       ^~~~~~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:751:73: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_ASSERT_UNREACHABLE(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:2804:3: note: in expansion of macro 'VM_ASSERT_UNREACHABLE'
   VM_ASSERT_UNREACHABLE(vm);
   ^~~~~~~~~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:732:75: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_NOT_IMPLEMENTED(vm) (MVM_FATAL_ERROR(vm, MVM_E_NOT_IMPLEMENTED), -1)
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:3008:7: note: in expansion of macro 'VM_NOT_IMPLEMENTED'
       VM_NOT_IMPLEMENTED(vm);
       ^~~~~~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:732:75: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_NOT_IMPLEMENTED(vm) (MVM_FATAL_ERROR(vm, MVM_E_NOT_IMPLEMENTED), -1)
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:3021:7: note: in expansion of macro 'VM_NOT_IMPLEMENTED'
       VM_NOT_IMPLEMENTED(vm);
       ^~~~~~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:751:73: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_ASSERT_UNREACHABLE(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:3027:3: note: in expansion of macro 'VM_ASSERT_UNREACHABLE'
   VM_ASSERT_UNREACHABLE(vm);
   ^~~~~~~~~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:1475:20: error: operation on 'pStackPointer' may be undefined [-Werror=sequence-point]
     *(pStackPointer++) = (v); \
      ~~~~~~~~~~~~~~^~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:1487:5: note: in expansion of macro 'PUSH'
     PUSH((uint16_t)(uintptr_t)pStackPointer - (uint16_t)(uintptr_t)pFrameBase); \
     ^~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:3323:3: note: in expansion of macro 'PUSH_REGISTERS'
   PUSH_REGISTERS(regLP1);
   ^~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c: In function 'vm_getStringData':
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:751:73: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_ASSERT_UNREACHABLE(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:5633:7: note: in expansion of macro 'VM_ASSERT_UNREACHABLE'
       VM_ASSERT_UNREACHABLE(vm);
       ^~~~~~~~~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c: In function 'vm_allocString':
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:5677:38: warning: suggest braces around empty body in an 'if' statement [-Wempty-body]
     TABLE_COVERAGE(sizeBytes, 3, 525); // Hit 2/3
                                      ^
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c: In function 'getProperty':
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:732:75: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_NOT_IMPLEMENTED(vm) (MVM_FATAL_ERROR(vm, MVM_E_NOT_IMPLEMENTED), -1)
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:5804:9: note: in expansion of macro 'VM_NOT_IMPLEMENTED'
         VM_NOT_IMPLEMENTED(vm);
         ^~~~~~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:5874:19: warning: comparison is always false due to limited range of data type [-Wtype-limits]
         if (index < 0) {
                   ^
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c: In function 'setProperty':
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:732:75: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_NOT_IMPLEMENTED(vm) (MVM_FATAL_ERROR(vm, MVM_E_NOT_IMPLEMENTED), -1)
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:5986:9: note: in expansion of macro 'VM_NOT_IMPLEMENTED'
         VM_NOT_IMPLEMENTED(vm);
         ^~~~~~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:6144:19: warning: comparison is always false due to limited range of data type [-Wtype-limits]
         if (index < 0) {
                   ^
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c: In function 'vm_stringSizeUtf8':
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:751:73: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_ASSERT_UNREACHABLE(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:6422:7: note: in expansion of macro 'VM_ASSERT_UNREACHABLE'
       VM_ASSERT_UNREACHABLE(vm);
       ^~~~~~~~~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c: In function 'toInt32Internal':
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:732:75: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_NOT_IMPLEMENTED(vm) (MVM_FATAL_ERROR(vm, MVM_E_NOT_IMPLEMENTED), -1)
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:6476:7: note: in expansion of macro 'VM_NOT_IMPLEMENTED'
       VM_NOT_IMPLEMENTED(vm); break;
       ^~~~~~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:732:75: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_NOT_IMPLEMENTED(vm) (MVM_FATAL_ERROR(vm, MVM_E_NOT_IMPLEMENTED), -1)
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:6480:7: note: in expansion of macro 'VM_NOT_IMPLEMENTED'
       VM_NOT_IMPLEMENTED(vm); break;
       ^~~~~~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:732:75: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_NOT_IMPLEMENTED(vm) (MVM_FATAL_ERROR(vm, MVM_E_NOT_IMPLEMENTED), -1)
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:6484:7: note: in expansion of macro 'VM_NOT_IMPLEMENTED'
       VM_NOT_IMPLEMENTED(vm); break;
       ^~~~~~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:732:75: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_NOT_IMPLEMENTED(vm) (MVM_FATAL_ERROR(vm, MVM_E_NOT_IMPLEMENTED), -1)
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:6488:7: note: in expansion of macro 'VM_NOT_IMPLEMENTED'
       VM_NOT_IMPLEMENTED(vm); break;
       ^~~~~~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:733:63: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_RESERVED(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:6512:7: note: in expansion of macro 'VM_RESERVED'
       VM_RESERVED(vm); break;
       ^~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:733:63: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_RESERVED(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:6516:7: note: in expansion of macro 'VM_RESERVED'
       VM_RESERVED(vm); break;
       ^~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:751:73: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_ASSERT_UNREACHABLE(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:6555:7: note: in expansion of macro 'VM_ASSERT_UNREACHABLE'
       VM_ASSERT_UNREACHABLE(vm);
       ^~~~~~~~~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c: In function 'mvm_equal':
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:751:73: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define VM_ASSERT_UNREACHABLE(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:6771:7: note: in expansion of macro 'VM_ASSERT_UNREACHABLE'
       VM_ASSERT_UNREACHABLE(vm);
       ^~~~~~~~~~~~~~~~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c: At top level:
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:1285:13: warning: 'loadPtr' declared 'static' but never defined [-Wunused-function]
 static void loadPtr(VM* vm, uint8_t* heapStart, Value* pValue);
             ^~~~~~~
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c: In function 'mvm_call':
/tmp/esp-microvium-test/components/microvium/dist-c/microvium.c:3407:15: error: 'reg1F' may be used uninitialized in this function [-Werror=maybe-uninitialized]
       reg1F = pow(reg1F, reg2F);
               ^~~~~~~~~~~~~~~~~

```

**Comment by coder-mike** [comment] 2022-06-22 22:43
@morganrallen Thanks for the detailed output. What compiler are you using?

**Comment by morganrallen** [comment] 2022-06-22 22:51
This was built against ESP-IDF v4.4.2 which ships `xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0`

**Comment by coder-mike** [comment] 2022-06-22 23:28
Thanks, that helps a lot. I'll try to reproduce those errors on my end and work through them.

**Comment by morganrallen** [comment] 2022-06-23 20:09
Can you explain the error handling macros? I haven't fully parsed them yet but it appears it can results in statements that looking `return something, -1` Where `something` is some value returned from another macro like `VM_ASSERT_UNREACHABLE`

**Comment by coder-mike** [comment] 2022-06-23 20:26
Ok, I've made the change. Maybe this will help with some of the errors.

https://github.com/coder-mike/microvium/commit/d43633ba32dd176e45cbe17f53855441ab2563d1

**Comment by coder-mike** [comment] 2022-06-23 20:50
Here's something interesting, just for curiosity. The int conversion is currently this:

```c
#define VIRTUAL_INT14_ENCODE(i) ((uint16_t)((i << 2) | 3))
```

It seems this is giving a warning due to `Wshift-negative-value`. That's fine, I can cast to an unsigned first:

```c
#define VIRTUAL_INT14_ENCODE(i) ((uint16_t)(((uint16_t)i << 2) | 3))
```

But then the Microvium ROM size grows by 20 bytes! I wasn't expecting that, since I thought the behavior should be the same. I speculate that the reason it's not the same is that I'm sometimes encoding a 32-bit int, which I know is in the 14-bit range but the compiler doesn't so it has to enforce the correct 16-bit overflow semantics for the shift if I use an unsigned shift.

So then I changed it to this:

```c
#define VIRTUAL_INT14_ENCODE(i) ((uint16_t)(((unsigned int)i << 2) | 3))
```

Then the size drops 24 bytes! That is, 4 bytes less than it was originally. 

Anyway, it seems that the semantics are still correct, so I've pushed this change to the repo. https://github.com/coder-mike/microvium/commit/dd21733683defe20673d5c543d27fe2db14a3741

**Comment by morganrallen** [comment] 2022-06-23 22:08
fantastic! I appear to having a working build. Hopefully I can find some time in the next day or two to do something with it

**Closed** 2022-06-27 10:39 UTC
